name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'URL to call to notify n8n that the workflow has completed.'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Debug Repository Contents
        run: |
          echo "Repository contents:"
          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Run Tests
        run: |
          echo "Running tests..."
          npm test

      - name: Wait for 60 seconds
        run: |
          echo "Waiting for 60 seconds..."
          sleep 60

      - name: Notify n8n to resume workflow
        if: always()  # Ensure this step runs even if previous steps fail
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            RESUME_URL="${{ github.event.inputs.resumeUrl }}"
            if [ -n "$RESUME_URL" ]; then
              echo "Calling n8n webhook URL: $RESUME_URL"
              curl -X POST "$RESUME_URL" \
                   -H "Content-Type: application/json" \
                   -d '{"status": "completed"}' \
                   --max-time 10 \  # Timeout after 10 seconds
                   --retry 3 \     # Retry up to 3 times
                   --retry-delay 5 # Wait 5 seconds between retries
            fi
          fi
