name: Docker Nightly Image CI
run-name: Build ${{ inputs.branch }} - ${{ inputs.user }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub branch to create image off.'
        required: true
        default: 'master'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'nightly'
      merge-master:
        description: 'Merge with master.'
        type: boolean
        required: true
        default: false
      callback-url:
        description: 'URL to call after workflow completes.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/images/n8n-custom/Dockerfile
          build-args: |
            N8N_RELEASE_TYPE=nightly
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.DOCKER_USERNAME }}/n8n:${{ env.N8N_TAG }}

      - name: Call Callback URL - optionally
        run: |
          if [[ "${{github.event.inputs.callback-url}}" != "" ]]; then
            curl -v -X POST -d 'status=success&run_id=${{ github.run_id }}' ${{github.event.inputs.callback-url}}
          else
            echo "No callback URL provided."
          fi
        shell: bash
